"""init tables

Revision ID: 9e5aad80191b
Revises: 
Create Date: 2026-03-18 18:52:58.342696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5aad80191b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('equipment_type', sa.String(length=255), nullable=True),
    sa.Column('max_load_capacity', sa.Float(), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_name'), ['asset_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_equipment_type'), ['equipment_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM_ADMIN', 'ASSET_MANAGER', 'ENGINEER', name='userrole'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('evaluation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planned_load', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', name='evaluationstatus'), nullable=False),
    sa.Column('overload_percentage', sa.Float(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_logs_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_logs_evaluated_at'), ['evaluated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_logs_evaluated_at'))
        batch_op.drop_index(batch_op.f('ix_evaluation_logs_asset_id'))

    op.drop_table('evaluation_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_company_id'))

    op.drop_table('users')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_equipment_type'))
        batch_op.drop_index(batch_op.f('ix_assets_company_id'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_name'))

    op.drop_table('assets')
    op.drop_table('companies')
    # ### end Alembic commands ###
